name: Sync wiki

on:
  push:
    branches:
      - main
    paths:
      - 'wiki/**'
      - 'README.md'

jobs:
  sync:
    if: github.repository == 'AttackingOrDefending/wiki-sync'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Checkout wiki
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository }}.wiki"
          path: "wiki-sync.wiki"
      - name: Set github bot global config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "actions-user"
      - name: Sync all files to wiki
        run: |
          cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/lichess-bot.wiki
          cp -r $GITHUB_WORKSPACE/wiki/* $GITHUB_WORKSPACE/lichess-bot.wiki
          cd $GITHUB_WORKSPACE/lichess-bot.wiki
          git add .
          git commit -m "Auto update wiki"
          git push
          git add .
          git commit -m "Auto update wiki (${{ github.event.head_commit.message }})"
          git push
