name: Sync wiki

on:
  push:
    branches:
      - main
    paths:
      - 'wiki/**'
      - 'README.md'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Checkout wiki
        uses: actions/checkout@v3
        with:
          repository: "${{ github.repository }}.wiki"
          path: "wiki-sync.wiki"
      - name: Sync files to wiki
        run: |
          git config --global user.email "40605232+AttackingOrDefending@users.noreply.github.com"
          git config --global user.name "AttackingOrDefending"
          git remote set-url origin ${{ secrets.ssh }}
          cp -r $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/wiki/Home.md
          cp -r $GITHUB_WORKSPACE/wiki/* $GITHUB_WORKSPACE/wiki-sync.wiki
          git add .
          git commit -m "Update wiki"
          git push origin
          cd $GITHUB_WORKSPACE/wiki-sync.wiki
          git remote set-url origin ${{ secrets.ssh2 }}
          git add .
          git commit -m "Update wiki"
          git push origin
