name: Sync wiki

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Copy
        run: cp README.md wiki/Home.md
      - name: Sync files to wiki
        run: |
          git config --global user.email "40605232+AttackingOrDefending@users.noreply.github.com"
          git config --global user.name "AttackingOrDefending"
          git remote set-url origin ${{ secrets.ssh }}
          git add wiki/Home.md
          git commit -m "Copy"
          git push origin HEAD:main
